-- CreateTable
CREATE TABLE "Palette" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "genColors" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
